-- ==========================================
-- FORGE PROTOCOL: COMPLETE DATABASE SCHEMA
-- ==========================================

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS profiles (
  wallet_address TEXT PRIMARY KEY,
  name TEXT,
  title TEXT,
  bio TEXT,
  avatar_url TEXT,
  twitter TEXT,
  github TEXT,
  discord TEXT,
  telegram TEXT,
  profile_sbt_mint TEXT,
  tech_stack TEXT,
  forge_score INTEGER DEFAULT 0,
  rank INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tasks Table
CREATE TABLE IF NOT EXISTS tasks (
  pda TEXT PRIMARY KEY,
  task_id BIGINT,
  client TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  amount BIGINT,
  difficulty SMALLINT,
  contact_info TEXT,
  listing_deadline TIMESTAMPTZ,
  task_type TEXT DEFAULT 'challenge',
  expected_days INTEGER,
  skills JSONB DEFAULT '[]'::jsonb,
  ai_analysis JSONB,
  content_hash TEXT,
  status TEXT DEFAULT 'Open',
  dispute_reason TEXT,
  dispute_count INTEGER DEFAULT 0,
  escalated_to_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Task Applicants Table
CREATE TABLE IF NOT EXISTS task_applicants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_pda TEXT NOT NULL REFERENCES tasks(pda) ON DELETE CASCADE,
  worker_address TEXT NOT NULL,
  estimated_days INTEGER,
  message TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(task_pda, worker_address)
);

-- 4. Rankings Table
CREATE TABLE IF NOT EXISTS rankings (
  wallet_address TEXT PRIMARY KEY REFERENCES profiles(wallet_address) ON DELETE CASCADE,
  forge_score INTEGER DEFAULT 0,
  tasks_completed INTEGER DEFAULT 0,
  rank INTEGER,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Storage Bucket: nft-metadata
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'nft-metadata',
  'nft-metadata',
  true,
  5242880, -- 5MB limit
  ARRAY['application/json', 'image/png', 'image/jpeg', 'image/webp', 'image/svg+xml']
)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies for nft-metadata
CREATE POLICY "Public read access for nft-metadata"
ON storage.objects FOR SELECT
USING (bucket_id = 'nft-metadata');

CREATE POLICY "Authenticated users can upload nft-metadata"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'nft-metadata');

CREATE POLICY "Authenticated users can update their nft-metadata"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'nft-metadata');

-- (Optional) Storage Bucket: avatars
-- Assuming avatars are uploaded directly to an avatars bucket based on frontend code
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'avatars',
  'avatars',
  true,
  5242880,
  ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml']
)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public read access for avatars"
ON storage.objects FOR SELECT
USING (bucket_id = 'avatars');

CREATE POLICY "Authenticated users can upload avatars"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'avatars');

CREATE POLICY "Authenticated users can update avatars"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'avatars');
